tunnel: your-tunnel-name
credentials-file: C:\Users\sirtheprogrammer\.cloudflared\credentials.json
origincert: C:\Users\sirtheprogrammer\.cloudflared\cert.pem

ingress:
  - hostname: your-domain.com
    service: http://localhost:5000
  - service: http_status:404 
  